replicaCount: 1

image:
  repository: abdelhakachourhorizon/pygrpc-library
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: ClusterIP
  port: 50051
  metricsport: 8000

resources:
  limits:
    cpu: 120m
    memory: 256Mi
  requests:
    cpu: 120m
    memory: 256Mi

autoscaling:
  enabled: false
